### ISSUE TITLE
Handle the upcoming changes in ember-cli 2.6

### ISSUE THREAD

**Issue by kimroen** [kimroen/ember-cli-coffeescript#110]
The blueprints are moved to this addon, and some internal changes are made:

https://github.com/ember-cli/ember-cli-legacy-blueprints

I'm not yet sure what the extent of the changes are, but they seem relatively big. Especially the addition of direct support for different testing libraries is curious - I'm not sure if it makes sense to support these in ember-cli-coffeescript as well.

What are other addons that overwrite the main blueprints doing?

**Comment by nathanhammond** [comment]
I can't ever recommend overwriting the main blueprints and instead recommend building alongside them. Our goal now is to actually have addons themselves bundle the blueprints that they want to ship, which means that we don't have to release simultaneously to update blueprints when they change in a new dependent library version. Eventually this will include Ember and Ember CLI itself. At that point we'd extract the last stalwart blueprints (namely app and addon) from ember-cli itself and move them into their own addon. This will help make ember-cli more framework agnostic, which is important as more of the JS community forks ember-cli.

**Comment by kimroen** [comment]
I consider this solved now, and addressed in the latest version of `ember-cli-coffeescript`.

Longer-term, I still think we'll need to split things up a bit to make this more sustainable in the future. Hopefully I can find someone that's using CoffeeScript and Ember in production to help out, and I'll also talk to people running similar projects, like `ember-cli-typescript`.
