### ISSUE TITLE
blueprints not working in ember 2.7.0 

### ISSUE THREAD

**Issue by blackode** [kimroen/ember-cli-coffeescript#117]
All ember generators not working after installing `ember-cli-coffeescript`
Here the following error screen shot 
![screenshot from 2016-08-24 15-02-44](https://cloud.githubusercontent.com/assets/9107477/17925801/04b15bb8-6a0c-11e6-9fa6-2b6b042c19c7.png)

**Comment by alobaidizt** [comment]
I have the same issue

**Comment by alobaidizt** [comment]
@blackode it turns out this issue was solved 9 days ago. [#115](https://github.com/kimroen/ember-cli-coffeescript/pull/115)

you can fix your project by replacing your `ember-cli-coffeescript` hash with ```    "ember-cli-coffeescript": "kimroen/ember-cli-coffeescript#ebb4abd237599ae7bd3a852cd71d63924a79851f",
```

**Comment by blackode** [comment]
@alobaidizt thanks for the help it is absolutely right  .  Now generator are working but the issue is when I run the server is ti is raising the following error
ERROR SCREEN SHOT
![broc](https://cloud.githubusercontent.com/assets/9107477/17996782/92d5fbf6-6b88-11e6-9390-e3c7f02f3029.png)

**Comment by alobaidizt** [comment]
Your second issue doesn't belong here. But I'd say try running the following in your project directory:

npm uninstall ember-simple-auth
npm cache clean
ember install ember-simple-auth

Then try serving it  again

**Comment by blackode** [comment]
@alobaidizt  Thanks for the help . I tried as you stated  ,but nothing changed same error raised again .......

**Comment by alobaidizt** [comment]
@blackode it looks like it's a symbolic link issue. I would delete `application.js` file found under tmp directory. If that's not enough then you'll have to unlink it since that's the root of the issue.

**Comment by kimroen** [comment]
@blackode Sorry for not jumping in earlier. This is a known issue, which shows up frequently with ember-simple-auth. You can see a description of what's going on here, but the short version is that you should probably use JavaScript for that particular file. More details: https://github.com/kimroen/ember-cli-coffeescript/issues/87#issuecomment-158794463

@alobaidizt Thank you very much for helping out!

**Comment by kimroen** [comment]
I'll keep this open until the fix for your original issue is released, though.

**Comment by blackode** [comment]
@kimroen Thanks for everything ........

**Comment by erichonkanen** [comment]
+1 and on a positive note it's good to know that some other people are still holding out and using coffeescript!!!

**Comment by blackode** [comment]
@erichonkanen coffescript saves the time and we can use that time to drink the coffee...........

**Comment by erichonkanen** [comment]
@blackode yes it does... and it's cleaner, easier to read, easier to write, more fun to use, less "hip" but more "cool"

**Comment by erichonkanen** [comment]
is there any movement on this? blueprints still not working

**Comment by blackode** [comment]
@erichonkanen i think not yet. I hope they are working on this.......

**Comment by erichonkanen** [comment]
what is the issue that needs fixing? it'd be nice to fix it

**Comment by kimroen** [comment]
This has now been resolved in `v1.15.0`, that was just published. Luckily, we were able to solve this in a way that is backwards-compatible :tada:

Sorry for the lack of response in here, and thank you for helping each other out.

**Comment by blackode** [comment]
@kimroen  Thanks for the update ......  (:

**Comment by alobaidizt** [comment]
Wonderful work @kimroen! Thank you!
