### ISSUE TITLE
Change name of ember npm package in `after`

### ISSUE THREAD

**Issue by kimroen** [kimroen/ember-cli-coffeescript#121]
This has landed now: https://github.com/emberjs/ember.js/pull/13022

The name of the addon providing ember in the future is going to be `ember-source`, and so we need to add`ember-source` inside `after` in the `ember-addon`-section of `package.json` to make sure we continue overriding the blueprints.

[The section in question](https://github.com/kimroen/ember-cli-coffeescript/blob/1d6d0fa1cf8cd1e192195123cc4752ac2cdc866e/package.json#L72).

**EDIT:** Accommodate the suggestion by @locks.

**Comment by locks** [comment]
A small note that you might want to keep `ember` to make sure it works with version of Ember older than v2.10 (the predicted release).

**Comment by kimroen** [comment]
Thanks, Ricardo! Good point, let's keep them both.
