### ISSUE TITLE
Who is still holding out and using coffeescript with Ember? 

### ISSUE THREAD

**Issue by erichonkanen** [kimroen/ember-cli-coffeescript#125]
Just curious! I've been losing the battles in fighting for keeping it as the overall trend has shifted away :/

**Comment by olleolleolle** [comment]
Hi, @erichonkanen, this is a project issue tracker, and this is not registering a software defect. (And, answering: lots of people use CoffeeScript with Ember.)

This issue is perhaps closable, @kimroen?

**Comment by mriska** [comment]
We are still using coffeescript for all our projects. I think it still offers advantages over ES6, although a lot less now than with older JS versions.
