### ISSUE TITLE
Update broccoli-coffee dependency to 0.7.0

### ISSUE THREAD

**Issue by ralmidani** [kimroen/ember-cli-coffeescript#126]
The latest version (0.7.0) of broccoli-coffee uses CoffeeScript v1.11.1, which enables us to do module imports and exports without using backticks.

Is there a plan to update this dependency soon, or do we need to update the blueprint framework along with changing the dependency?

**Comment by kimroen** [comment]
Yeah, it's very exciting! There's a pull request for it right over here, that I might get to and release this weekend. That's my hope, anyway!

https://github.com/kimroen/ember-cli-coffeescript/pull/124

**Comment by ralmidani** [comment]
Looking forward to it! Thank you!
