### ISSUE TITLE
Update README now that import/export are in CoffeeScript

### ISSUE THREAD

**Issue by wavebeem** [kimroen/ember-cli-coffeescript#127]
Now that CoffeeScript 1.11.1 is out with import/export support, it might be nice to remove the backtick stuff from the README

**Comment by kimroen** [comment]
Yeah, I agree! It's being done as part of this PR over here where we also update the blueprints: https://github.com/kimroen/ember-cli-coffeescript/pull/124

Thanks!

**Comment by kimroen** [comment]
This has now been merged 🎉

**Comment by wavebeem** [comment]
🎉🎉
