### ISSUE TITLE
ember server freezes on windows in v1.15.0 after creating component

### ISSUE THREAD

**Issue by rafaeltnk** [kimroen/ember-cli-coffeescript#130]
I've just installed ember-cli v2.8.0 on Windows 8.1 and i've created a dummy application. 
After installing this addon (v1.15.0) and create a simple component when I run ember server on PowerShell the application keep loading on localhost:4200 and doesn't show anything. 
In PowerShell the trees infos is not showing up, it's just froze with the message "Serving on http://localhost:4200/". 
When I destroy the component (via ember d component my-component) the application back to work.
I've tested in OSX and Ubuntu, it seems be an issue only in Windows. 
Someone has a solution for it?

ember-cli-coffeescript: 1.15.0
ember-cli: 2.8.0
node: 6.9.2
os: win32 x64 - windows 8.1

**Comment by kimroen** [comment]
Hmm. Sorry, I'm at a bit of a loss on this one - I don't really have a good way to try this out. Does the page load normally if you don't install ember-cli-coffeescript and create a component?

**Comment by rafaeltnk** [comment]
Hi! Thanks for you reply.

Yes, if I don't install and create a component the page loads normally. After installing the Coffeescript and generating anything via ember-cli (now I've noticed that this is not only a specific problem of component generation) the page keeps in "loading" state and never finish. The page doesn't show anything. 

I got around installing a previous version (1.13.1) on the Windows computer. I can't create new things via ember-cli but at least the page loads in this way.

Thanks!

**Comment by boris-petrov** [comment]
This issue is the same as #112. There is a pull-request to fix this but no one seems to care.

**Comment by kimroen** [comment]
I'll close this in favor of #112 to keep discussion contained.

> There is a pull-request to fix this (in broccoli-coffee) but no one seems to care.

Stefan gave feedback on the PR, but I poked him to make a more explicit decision about it. I don't think the inaction comes from a lack of care, though.
