### ISSUE TITLE
Generator for resource

### ISSUE THREAD

**Issue by alexphys** [kimroen/ember-cli-coffeescript#21]
When I run

>ember generate resource ingredients.

I got an error saying

>no such file or directory "path-to-app/my-app/app/router.js"

This happens only when I'm trying to generate a resource. When trying to generate a route all is working perfectly, a route is being added inside my router.coffee file and the route and template files are being generated perfectly as coffee.

Anyone else noticed this?

**Comment by nathanpalmer** [comment]
@kimroen You need to set the project within install

```
  install: function(options) {
    this.project = options.project;
    return this._process('install', options);
  },
```

**Comment by kimroen** [comment]
@nathanpalmer I could kiss you.

**Comment by kimroen** [comment]
This should work again now with ember-cli-coffeescript 0.8.0.

Not pretty - hopefully I can delete all this code again in the future.
