### ISSUE TITLE
When does coffeelinting happen?

### ISSUE THREAD

**Issue by DVG** [kimroen/ember-cli-coffeescript#43]
I feel like I'm missing something here. The README gives the impression that coffeelinting should be automatic if there is a coffeelint.json file present in the project directory. I have one:

```
{
  "no_backticks": {
    "level": "ignore"
  }
}
```

Which is fine, I can run coffeelint app/ and get the appropriate results. However I got the impression that this should just happen when the coffeescript is preprocessed:

> If you have a coffeelint.json file we will automatically pick up on it and start running linting.

So my question is really just when does this happen? The code seems to suggest that there will be a linting informational message:

https://github.com/kimroen/ember-cli-coffeescript/blob/master/lib/coffee-linter.js#L42

But I do not see that happening, when I preprocess CS by, say, starting the server. What am I missing?

**Comment by kimroen** [comment]
If you have a `coffeelint.json`-file in the root of your project directory, then the linting should take place on the app-files and the test-files when you run the server, and on the app-files when you run a build.

For instance - here is the output when I run `ember s`:

```
version: 0.1.5
Livereload server on port 35729
Serving on http://0.0.0.0:4200/


=======================================================
Linting completed on 177 files with  0  errors.
=======================================================



=======================================================
Linting completed on 82 files with  0  errors.
=======================================================


Build successful - 7223ms.
```

…and then again on the files that change.

Things to check:
- Is the `coffeelint.json`-file in the root of your project?
- Is the other functions of `ember-cli-coffeescript` being run (such as compiling the coffeescript-files)?

**Comment by kimroen** [comment]
I will close this - please reopen if you're still having issues getting linting to work.

**Comment by DVG** [comment]
This is what I get when running ember serve

```
~/code/projects/my-project: ember serve --proxy http://localhost:3000
version: 0.1.5
Could not find watchman, falling back to NodeWatcher for file system events
Proxying to http://localhost:3000
Livereload server on port 35729
Serving on http://0.0.0.0:4200/my-project/
Build successful - 4018ms.
Slowest Trees                  | Total          
-------------------------------+----------------
ES6Modules                     | 706ms          
SassCompiler                   | 631ms          
CoffeeScriptFilter             | 595ms          
Class                          | 365ms          
TemplateCompiler               | 353ms     
```

coffeeline.json (in project root directory)

```
{
  "no_backticks": {
    "level": "ignore"
  },
  "max_line_length": {
    "level": "ignore"
  }
}
```

package.json
```
{
  "name": "my-project",
  "version": "0.0.0",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "start": "ember server",
    "build": "ember build",
    "test": "ember test"
  },
  "repository": "https://github.com/stefanpenner/ember-cli",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "body-parser": "^1.2.0",
    "broccoli-asset-rev": "0.3.1",
    "broccoli-ember-hbs-template-compiler": "^1.6.1",
    "broccoli-sass": "0.3.2",
    "ember-cli": "^0.1.5",
    "ember-cli-bourbon": "0.0.5",
    "ember-cli-coffeescript": "^0.2.0",
    "ember-cli-emblem": "0.0.2",
    "ember-cli-ic-ajax": "0.1.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-mocha": "^0.1.4",
    "ember-cli-moment": "0.0.1",
    "ember-cli-pretender": "^0.3.1",
    "ember-cli-sass": "^3.0.3",
    "ember-cli-simple-auth": "^0.7.1",
    "ember-cli-simple-auth-testing": "^0.7.1",
    "ember-data": "1.0.0-beta.11",
    "ember-export-application-global": "^1.0.0",
    "express": "^4.8.5",
    "glob": "^4.0.5",
    "growl": "^1.8.1",
    "grunt": "^0.4.5",
    "grunt-exec": "^0.4.6",
    "grunt-git": "^0.3.1",
    "node-sass": "1.1.2"
  },
  "dependencies": {
    "ember-cli-bootstrap-components": "0.0.3",
    "ember-cli-flash-messages": "^0.1.1"
  }
}
```

**Comment by kimroen** [comment]
I see. Well, I see in you `package.json` that `ember-cli-coffeescript` is set to version `^0.2.0`, but linting was [introduced in version `0.3.0`](https://github.com/kimroen/ember-cli-coffeescript/blob/master/CHANGELOG.md#030) of this project (the newest version is `0.7.0`).

There's been some nice improvements, so I recommend you upgrade. Hopefully that helps :)

**Comment by DVG** [comment]
Makes sense! Thanks!
