### ISSUE TITLE
Add blurb in README about export/import statements needed for ES6 modules.

### ISSUE THREAD

**Issue by rwjblue** [kimroen/ember-cli-coffeescript#44]

**Comment by kimroen** [comment]
I'm not sure I follow - just something that explains that you need them, or how they are different when using coffeescript? Did something happen to trigger this request that I should aim to solve?

**Comment by rwjblue** [comment]
Not really, I just referenced the README for "how to use coffeescript with ember-cli" in https://twitter.com/rwjblue/status/552487393274896384, but it really doesn't say how...

**Comment by kimroen** [comment]
Thanks!
