### ISSUE TITLE
Repeated CoffeeLint-results (app and test) is potentially confusing

### ISSUE THREAD

**Issue by ninjatronic** [kimroen/ember-cli-coffeescript#47]
When coffeelint is included I get output like this:

```
==========================================
File: vapour/components/data-map.coffee
==========================================
 Line exceeds maximum allowed length (error) 
Line:  22

 Line exceeds maximum allowed length (error) 
Line:  25

 Line exceeds maximum allowed length (error) 
Line:  50

 Operators must be spaced properly (error) 
Line:  54

 Operators must be spaced properly (error) 
Line:  54

 Line exceeds maximum allowed length (error) 
Line:  54

 Line exceeds maximum allowed length (error) 
Line:  64

 Line exceeds maximum allowed length (error) 
Line:  102

 Operators must be spaced properly (error) 
Line:  112


=======================================================
Linting completed on 1 files with  9  errors.
=======================================================



=======================================================
Linting completed on 0 files with  0  errors.
=======================================================
```

**Comment by kimroen** [comment]
Hi! Yeah, that first one is linting your app files, and then the second one is the test-files.

As far as I know, there's no way to tell the difference within the addon, but I would love to indicate this somehow. Just not sure how. If you have ideas, please share! :)

Something we _could_ do here is not output anything when there were no files - that would probably make this a bit less confusing.

**Comment by ninjatronic** [comment]
Ah I see! That makes much more sense.

i don't know enough about ember-cli off the top of my head to suggest anything, sorry, but perhaps there is some info on the [`inputTree` parameter on the CoffeeScriptLinter](https://github.com/kimroen/ember-cli-coffeescript/blob/master/lib/coffee-linter.js#L11)?

**Comment by kimroen** [comment]
I will try to think of something for the next time I work on this - thanks!

**Comment by ninjatronic** [comment]
Thanks to you for the lib

**Comment by kimroen** [comment]
I will add a quick note in the README about this. Ember-cli has a new system for linting now which I will take a look at implementing later, but hopefully using that will make things clearer.
