### ISSUE TITLE
Issue with import/export variable name collision.

### ISSUE THREAD

**Issue by artsyca** [kimroen/ember-cli-coffeescript#48]
Summary: Overriding an imported variable now has unexpected results.

Steps to reproduce:
In the latest cli (0.1.11) import a module, extend it and export using the same name:
```coffee
`import MyCustomComponent from 'my-custom-component/components/my-custom-component'`

MyCustomComponent = MyCustomComponent.extend ...

`export MyCustomComponent`
```
This was a typical workflow in addons allowing addon modules to be merged into the source tree but also remain extensible due to not being overwritten by local copies in the parent app.

This behaviour breaks now, because instead of assigning imports to the variable defined in the import statement, (i.e. `MyCustomComponent`) They are being assigned to `MyCustomComponent['default']`, ostensibly to eliminate an unnecessary variable declaration.

While this is not a problem with JS blueprints which can export directly without assigning to a similarly named var (a limitation of coffee due to the need for backticks in import/export statements), it causes terrible things to happen in coffeescript whereby the local variable clobbers the import and causes the code to stop working.

Essentially it's not really safe to import a variable and then overwrite it using coffeescript and although this is an edge case I just wanted to report the issue in the hope of establishing a best practice for dealing with this.

**Comment by kimroen** [comment]
That is interesting. I'm not sure why you need to keep the same variable name for your exported class though. Where would this file be placed?

What do you do to avoid this?

I'm not sure what to do about this, but I appreciate you letting us know.

**Comment by artsyca** [comment]
@kimroen I'll give you a more concrete example: creating an addon `ember-cli-x-button`

When creating an addon, there are two important directories: the `/addon/` and `/app/` directories. Anything in the latter will be merged with the target source tree, anything in the former can be imported by invoking the name of the addon.

Typically, we'll write our code in

```coffee
/addon
    /components
        x-button.coffee
```

and then include a file in

```coffee
/app
    /components
        x-button.coffee
```
that merely includes the addon version and exports it as-is. This allows two benefits:

  * Our component is merged directly into the app tree and can be used immediately
  * It can be imported and overwritten in the target app without getting clobbered by (or clobbering) a file with the same name.

This behaviour is described here: https://gist.github.com/kristianmandrup/ae3174217f68a6a51ed5#components

Currently this works well enough even in coffeescript.

The problem arises if the consuming app wants to extend the component without renaming it. Or worse yet if the component is something like an adapter or model that doesn't take too well to being renamed.

Extending x-button example from the above link, consider `x-model`

```coffee
#target-app/adapters/x-model.js

`import Ember from 'ember'`
`import XModelAdapter from 'ember-xbutton/adapters/x-model'`

XModelAdapter = XModelAdapter.extend ... # This opens up a world of hurt.

`export default XModelAdapter`
```

Because now the generated javascript looks more like this:

```javascript
// target-app/adapters/x-model.js
import Ember from 'ember';
import XModelAdapter from 'ember-xbutton/adapters/x-model';

XModelAdapter = XModelAdapter['default'].extend ... 

// Any other instances of XModelAdapter['default'] in the code will now be undefined!
// Typically this affects static methods or things like fixtures etc that rely on the variable name.

export default XModelAdapter; // may not make it here.
```

This is mainly a coffeescript problem due to the nature of how `import` and `export` need to be used.
The only solution is to not reuse the internal variable name in the coffeescript blueprint, since it doesn't matter anyway:

```coffescript
___random_string___ = XModelAdapter['default'].extend()

...

`export default ___random_string___`
```

Just bringing this up here as it came up during our work on [ember-cli-dimple](https://github.com/rebaselabs/ember-cli-dimple) and I was quite taken aback by the breaking behaviour until I understood the reason behind it. I'm not very keen to have to watch out for this now but it's still somewhat of an edge case fwiw.

**Comment by artsyca** [comment]
Gonna close the issue. Thank you for helping me increase my understanding of the problem, and apologies for opening a bit of a nuisance issue.
