### ISSUE TITLE
Upgrade test blueprints

### ISSUE THREAD

**Issue by amk221** [kimroen/ember-cli-coffeescript#59]
Changes to `setup` and `teardown` functions, and `assert` passed in to test as an arg
http://qunitjs.com/upgrade-guide-2.x/

**Comment by kimroen** [comment]
There is actually already a pull request for this - waiting for ember-cli to release a new version to update. https://github.com/kimroen/ember-cli-coffeescript/pull/54

Thanks!

**Comment by amk221** [comment]
Apologies didn't spot!
ty
