### ISSUE TITLE
addon/ folder is ignored

### ISSUE THREAD

**Issue by igillis** [kimroen/ember-cli-coffeescript#73]
Hi all,

I'm creating an ember-cli addon in Coffeescript, and it seems that Coffeescript files in the `addon/` folder aren't being pre-processed. If I put .js files there, it works fine.

Has anyone successfully built an addon in Coffeescript before? Am I missing something?

**Comment by kimroen** [comment]
Hi! This should be resolved as of ember-cli-coffeescript 0.10.0. Could you confirm that this is the version you are using?

**Comment by kimroen** [comment]
I'll close this, but just reopen this if you're still having problems.
