### ISSUE TITLE
Generating route tries to generate an entry in route.js

### ISSUE THREAD

**Issue by kdabrowski** [kimroen/ember-cli-coffeescript#82]
Hey

I have an issue while generating routes in my app. Every time I run:

`ember g route example`

I'm getting the following:

```
 create app/templates/example.emblem
ENOENT, ../app/router.js'
Error: ENOENT, no such file or directory '../app/router.js'
```

Thanks in advance

**Comment by kimroen** [comment]
That is very interesting. I tried this now, and have no problems. Could you elaborate a bit?
