### ISSUE TITLE
Optionally disable blueprints

### ISSUE THREAD

**Issue by mmun** [kimroen/ember-cli-coffeescript#84]
In my app I use `ember-cli-coffeescript` to support older code, but all new code is written in ES6. The problem is that `ember g route posts` will always CoffeeScript blueprints. Is there a way to disable this behavior?

**Comment by kimroen** [comment]
Good plan, and there is; you can set `blueprints` to `false` in your config: https://github.com/kimroen/ember-cli-coffeescript#blueprints

**Comment by mmun** [comment]
@kimroen Thanks!
