### ISSUE TITLE
CoffeeScript not compiling files in in-repo-addon

### ISSUE THREAD

**Issue by tomoguisuru** [kimroen/ember-cli-coffeescript#94]
I recently ran into an issue where a I was using an in-repo-addon via git submodules. (It's a shared in-repo-addon with a bunch of common code that I use in different projects)

Both the app and the submodule were originally written in JavaScript. Growing tired of JS, I updated the main project to CoffeeScript by installing ember-cli-coffeescript. However, when I went to update the submodule I found that the CoffeeScript files weren't being compiled into JS.

Finding this strange, I created a new ember project, installed CoffeeScript, and then added a in-repo-addon via ember g in-repo-addon shared to test CoffeeScript on a new project. As expected, the `.coffee` files compiled without issue on the new repo.

I'm at a loss as to what I should do to get the other project working with CoffeeScript in the submodule/in-repo-addon. I've checked the configuration between the two projects and nothing stands out as to why CoffeeScript isn't working in the submodule. Stranger still is that it only seems to not compile the `shared/addon` folder. CoffeeScript placed in other folders will compile as expected

**Comment by kimroen** [comment]
I see your issue, but unfortunately I don't have any experience that immediately points me to what could be the problem. I'll look in to it in hopefully not too long, but just know that I don't really know if I'll find a solution.

Please let me know if you see any other differences.

**Comment by kimroen** [comment]
Can you confirm (just to be sure) that you have `ember-cli-coffeescript` as a `dependency` (not `devDependency` of the in-repo addon?

**Comment by kimroen** [comment]
Closing this for now, please reopen if you have checked the above and are still having issues.
